import bean.AndroidMobile;
import bean.Iphone;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AndroidMobile huaWeiMate = new AndroidMobile("huaWei", "red", "android");
        Iphone iphoneSE2 = new Iphone("iphoneSE", "red", "iPhone");
    }
}

